server:
  port: 8085
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/likelion-db
    username: qwer  SPRING_DATASOURCE_URL=jdbc:mysql://ec2-13-209-46-226.ap-northeast-2.compute.amazonaws.com:3306/likelion;SPRING_DATASOURCE_PASSWORD=hsy0408;SPRING_DATASOURCE_USERNAME=cvivis
    password: qwer

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update